PROJECT = ss_chat
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

DEPS = cowboy
dep_cowboy_commit = master

# Whitespace to be used when creating files from templates.
SP = 2

include erlang.mk
